import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import styles from './index.module.scss';
const RoomDetailDrawer = ({ isOpen, onClose, room }) => {
    if (!isOpen || !room) {
        return null;
    }
    const handleBackdropClick = (e) => {
        if (e.target === e.currentTarget) {
            onClose();
        }
    };
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: styles.backdrop, onClick: handleBackdropClick }), _jsxs("div", { className: styles.drawer, children: [_jsxs("div", { className: styles.header, children: [_jsxs("h3", { className: styles.title, children: [room.name, " - \u9009\u62E9\u5957\u9910"] }), _jsx("button", { className: styles.closeBtn, onClick: onClose, children: "\u2715" })] }), _jsxs("div", { className: styles.content, children: [_jsx("div", { className: styles.roomImage, children: _jsx("img", { src: room.image, alt: room.name, className: styles.image }) }), _jsxs("div", { className: styles.roomInfo, children: [_jsx("h4", { className: styles.roomName, children: room.name }), _jsxs("div", { className: styles.basicInfo, children: [_jsxs("span", { className: styles.param, children: ["\uD83D\uDCD0 ", room.area] }), _jsx("span", { className: styles.separator, children: "|" }), _jsxs("span", { className: styles.param, children: ["\uD83D\uDECF\uFE0F ", room.beds] }), _jsx("span", { className: styles.separator, children: "|" }), _jsxs("span", { className: styles.param, children: ["\uD83D\uDC65 ", room.guests] })] })] }), _jsxs("div", { className: styles.packageSelection, children: [_jsx("h4", { className: styles.selectionTitle, children: "\u8BF7\u9009\u62E9\u5957\u9910" }), [1, 2, 3].map((pkg) => (_jsx("div", { className: styles.packageOption, children: _jsxs("div", { className: styles.optionContent, children: [_jsxs("div", { className: styles.optionLeft, children: [_jsxs("div", { className: styles.packageBenefits, children: [room.showBreakfastTag && (_jsx("span", { className: `${styles.benefitTag} ${room.breakfastCount === 0 ? styles.breakfastNo : styles.breakfastYes}`, children: room.breakfastCount === 0 ? '无早餐' : `${room.breakfastCount}份早餐` })), room.showCancelTag && (_jsx("span", { className: `${styles.benefitTag} ${styles.cancelTag}`, children: "30\u5206\u949F\u514D\u8D39\u53D6\u6D88" }))] }), _jsx("div", { className: styles.serviceInfo, children: _jsx("span", { className: styles.serviceText, children: "\u4E0A\u6D77\u8FEA\u65AF\u5C3C\u4E50\u56ED\u4E13\u8F66\u63A5\u9001\u670D\u52A11\u4EFD" }) }), _jsx("div", { className: styles.confirmTag, children: _jsxs("span", { className: styles.confirmText, children: [pkg * 10, "\u5206\u949F\u786E\u8BA4"] }) })] }), _jsxs("div", { className: styles.optionRight, children: [_jsxs("div", { className: styles.priceInfo, children: [_jsxs("span", { className: styles.originalPrice, children: ["\u00A5", room.price + pkg * 100] }), _jsxs("span", { className: styles.discountedPrice, children: ["\u00A5", room.price + pkg * 50] }), _jsxs("span", { className: styles.discountBadge, children: ["\u7701", pkg * 50] })] }), _jsx("button", { className: styles.selectBtn, children: "\u9884\u8BA2" })] })] }) }, pkg)))] })] })] })] }));
};
export default RoomDetailDrawer;
//# sourceMappingURL=index.js.map