import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { HouseIcon, UserIcon, AreaIcon, BedIcon, BreakfastIcon } from '../../../icons';
import styles from './index.module.scss';
const RoomDrawerBasicInfo = ({ room, actualRoomName }) => {
    const displayRoomName = actualRoomName || room.name;
    return (_jsxs("div", { className: styles.basicInfo, children: [_jsxs("div", { className: styles.titleSection, children: [_jsx("h2", { className: styles.roomName, children: displayRoomName }), _jsxs("div", { className: styles.Breakfast, children: [_jsx("div", { className: styles.BreakfastIcon, children: _jsx(BreakfastIcon, { width: 20, height: 20, color: "#333333" }) }), "\u65E0\u65E9\u9910"] })] }), _jsxs("div", { className: styles.statsRow, children: [_jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: _jsx(AreaIcon, { width: 20, height: 20, color: "#333333" }) }), _jsxs("div", { className: styles.statContent, children: [_jsxs("span", { className: styles.statValue, children: ["\u516C\u5BD3\u2022", room.area] }), _jsx("span", { className: styles.statLabel, children: "\u6574\u5957\u623F\u5C4B" })] })] }), _jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: _jsx(HouseIcon, { width: 20, height: 20, color: "#333333" }) }), _jsx("div", { className: styles.statContent, children: _jsx("span", { className: styles.statValue, children: "3\u53671\u53852\u536B1\u53A8" }) })] }), _jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: _jsx(BedIcon, { width: 20, height: 20, color: "#333333" }) }), _jsx("div", { className: styles.statContent, children: _jsx("span", { className: styles.statValue, children: "5\u5E8A" }) })] }), _jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: _jsx(UserIcon, { width: 20, height: 20, color: "#333333" }) }), _jsx("div", { className: styles.statContent, children: _jsx("span", { className: styles.statValue, children: room.guests }) })] })] }), _jsx("div", { className: styles.bedSection, children: _jsxs("div", { className: styles.bedTable, children: [_jsxs("div", { className: styles.bedTableHeader, children: [_jsx("span", { className: styles.col1, children: "\u5367\u5BA4" }), _jsx("span", { className: styles.col2, children: "\u5E8A\u578B" }), _jsx("span", { className: styles.col3, children: "\u5C3A\u5BF8" }), _jsx("span", { className: styles.col4, children: "\u6570\u91CF" })] }), _jsx("div", { className: styles.bedTableBody, children: [
                                { room: '卧室1', bed: '大床', size: '1.8m', qty: '1张' },
                                { room: '卧室2', bed: '大床', size: '1.5m', qty: '2张' },
                                { room: '卧室3', bed: '大床', size: '1.5m', qty: '1张' },
                            ].map((item, idx) => (_jsxs("div", { className: styles.bedTableRow, children: [_jsx("span", { className: styles.col1, children: item.room }), _jsx("span", { className: styles.col2, children: item.bed }), _jsx("span", { className: styles.col3, children: item.size }), _jsx("span", { className: styles.col4, children: item.qty })] }, idx))) })] }) })] }));
};
export default RoomDrawerBasicInfo;
//# sourceMappingURL=index.js.map