import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import styles from './index.module.scss';
const RoomDrawerBasicInfo = ({ room }) => {
    return (_jsxs("div", { className: styles.basicInfo, children: [_jsxs("div", { className: styles.titleSection, children: [_jsx("h2", { className: styles.roomName, children: room.name }), _jsx("div", { className: styles.noBreakfast, children: "\u65E0\u65E9\u9910" })] }), _jsxs("div", { className: styles.statsRow, children: [_jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: "\uD83D\uDCCF" }), _jsx("span", { className: styles.statLabel, children: "\u516C\u5BD3" }), _jsx("span", { className: styles.statValue, children: room.area })] }), _jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: "\uD83D\uDECF\uFE0F" }), _jsx("span", { className: styles.statLabel, children: "\u623F\u95F4\u6570" }), _jsx("span", { className: styles.statValue, children: "3\u95F4" })] }), _jsxs("div", { className: styles.stat, children: [_jsx("span", { className: styles.statIcon, children: "\uD83D\uDC65" }), _jsx("span", { className: styles.statLabel, children: "\u6700\u591A\u5165\u4F4F" }), _jsx("span", { className: styles.statValue, children: room.guests })] })] }), _jsxs("div", { className: styles.bedSection, children: [_jsx("h3", { className: styles.sectionTitle, children: "\u5E8A\u578B\u8BE6\u60C5" }), _jsxs("div", { className: styles.bedTable, children: [_jsxs("div", { className: styles.bedTableHeader, children: [_jsx("span", { className: styles.col1, children: "\u5367\u5BA4" }), _jsx("span", { className: styles.col2, children: "\u5E8A\u578B" }), _jsx("span", { className: styles.col3, children: "\u5C3A\u5BF8" }), _jsx("span", { className: styles.col4, children: "\u6570\u91CF" })] }), _jsx("div", { className: styles.bedTableBody, children: [
                                    { room: '卧室1', bed: '大床', size: '1.8m', qty: '1张' },
                                    { room: '卧室2', bed: '大床', size: '1.5m', qty: '2张' },
                                    { room: '卧室3', bed: '大床', size: '1.5m', qty: '1张' },
                                ].map((item, idx) => (_jsxs("div", { className: styles.bedTableRow, children: [_jsx("span", { className: styles.col1, children: item.room }), _jsx("span", { className: styles.col2, children: item.bed }), _jsx("span", { className: styles.col3, children: item.size }), _jsx("span", { className: styles.col4, children: item.qty })] }, idx))) })] })] }), room.benefits && room.benefits.length > 0 && (_jsxs("div", { className: styles.benefitsSection, children: [_jsx("h3", { className: styles.sectionTitle, children: "\u623F\u578B\u6743\u76CA" }), _jsx("div", { className: styles.benefitsList, children: room.benefits.map((benefit, idx) => (_jsxs("span", { className: styles.benefitTag, children: ["\u2713 ", benefit] }, idx))) })] }))] }));
};
export default RoomDrawerBasicInfo;
//# sourceMappingURL=index.js.map