import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import DownArrowIcon from '../../../icons/DownArrowIcon';
import UpArrowIcon from '../../../icons/UpArrowIcon';
import { BedIcon, UserIcon } from '../../icons';
import styles from './index.module.scss';
const RoomCard = ({ room, isExpanded, onToggleExpand, onViewDetails, onOpenDetail, showLabel = true, }) => {
    // 只有套餐数为 1 时才显示预订按钮
    const showBookBtn = room.packageCount === 1;
    const handleCardClick = () => {
        onToggleExpand();
    };
    return (_jsx("div", { className: styles.card, onClick: handleCardClick, children: !isExpanded ? (
        /* 收起态 - 基础信息 */
        _jsxs("div", { className: styles.collapsedContent, children: [_jsx("div", { className: styles.imageArea, children: _jsx("img", { src: room.image, alt: room.name, className: styles.thumbnail }) }), _jsxs("div", { className: styles.infoArea, children: [_jsxs("div", { className: styles.nameRow, children: [_jsx("h4", { className: styles.roomName, children: room.name }), _jsx("button", { className: styles.expandToggleBtn, title: isExpanded ? '收起' : '展开', children: _jsx(DownArrowIcon, { width: 12, height: 12, color: "#B1B1B1" }) })] }), _jsxs("div", { className: styles.basicInfo, children: [_jsxs("span", { className: styles.param, children: [_jsx(BedIcon, { width: 14, height: 14, color: "#B1B1B1" }), " ", room.beds] }), _jsx("span", { className: styles.separator, children: "|" }), _jsxs("span", { className: styles.param, children: [_jsx(UserIcon, { width: 14, height: 14, color: "#B1B1B1" }), " ", room.guests] })] }), _jsxs("div", { className: styles.benefits, children: [room.showBreakfastTag && (_jsx("span", { className: `${styles.benefitTag} ${room.breakfastCount === 0 ? styles.breakfastNo : styles.breakfastYes}`, children: room.breakfastCount === 0 ? '无早餐' : `${room.breakfastCount}份早餐` })), room.showCancelTag && (_jsx("span", { className: `${styles.benefitTag} ${styles.cancelTag}`, children: "30\u5206\u949F\u514D\u8D39\u53D6\u6D88" }))] }), _jsxs("div", { className: styles.packageCountTag, children: [room.packageCount, "\u4E2A\u5957\u9910\u53EF\u9009"] }), _jsxs("div", { className: styles.footerRow, children: [showLabel && _jsxs("div", { className: styles.instantLabel, children: [room.confirmTime, "\u5185\u786E\u8BA4"] }), _jsxs("div", { className: styles.priceBlock, children: [_jsxs("span", { className: styles.price, children: ["\u00A5", room.priceList?.find(p => p.packageId === 1)?.currentPrice] }), _jsx("span", { className: styles.priceNote, children: room.priceNote })] }), showBookBtn && (_jsx("button", { className: styles.bookBtn, onClick: (e) => {
                                        e.stopPropagation();
                                        onViewDetails?.(room, room.packages?.[0]?.packageId);
                                    }, children: "\u9884\u8BA2" }))] })] })] })) : (
        /* 展开态 - 详细信息 */
        _jsxs("div", { className: styles.expandedContent, children: [_jsxs("div", { className: styles.expandedNameRow, children: [_jsx("h4", { className: styles.expandedRoomName, children: room.name }), _jsx("button", { className: styles.expandToggleBtn, title: "\u6536\u8D77", children: _jsx(UpArrowIcon, { width: 12, height: 12, color: "#B1B1B1" }) })] }), _jsx("div", { className: styles.carousel, children: _jsx("img", { src: room.image, alt: room.name, className: styles.expandedImage }) }), _jsxs("div", { className: styles.detailParams, children: [_jsxs("div", { className: styles.paramRow, children: [_jsx("span", { className: styles.paramLabel, children: "\u9762\u79EF" }), _jsx("span", { className: styles.paramValue, children: room.area })] }), _jsxs("div", { className: styles.paramRow, children: [_jsx("span", { className: styles.paramLabel, children: "\u5E8A\u578B" }), _jsx("span", { className: styles.paramValue, children: room.beds })] }), _jsxs("div", { className: styles.paramRow, children: [_jsx("span", { className: styles.paramLabel, children: "\u4EBA\u6570" }), _jsx("span", { className: styles.paramValue, children: room.guests })] })] }), _jsxs("div", { className: styles.packageList, onClick: (e) => e.stopPropagation(), children: [_jsxs("h4", { className: styles.packageTitle, children: [room.packageCount, "\u4E2A\u5957\u9910\u53EF\u9009"] }), (room.packages || []).slice(0, room.packageCount).map((pkg) => (_jsxs("div", { className: styles.packageItem, onClick: () => onOpenDetail?.(room, pkg.packageId), children: [_jsxs("div", { className: styles.packageLeft, children: [pkg.showPackageDetail && _jsx("span", { className: styles.hasPackageTag, children: "\u6709\u5957\u9910" }), _jsx("div", { className: styles.packageService, children: pkg.name }), _jsxs("div", { className: styles.packageBenefits, children: [pkg.showBreakfastTag && (_jsx("span", { className: `${styles.pkgBenefitTag} ${pkg.breakfastCount === 0 ? styles.breakfastNo : styles.breakfastYes}`, children: pkg.breakfastCount === 0 ? '无早餐' : `${pkg.breakfastCount}份早餐` })), pkg.showCancelTag && (_jsxs("span", { className: `${styles.pkgBenefitTag} ${styles.cancelTag}`, children: [pkg.cancelMunite, "\u5206\u949F\u514D\u8D39\u53D6\u6D88"] }))] }), _jsx("div", { className: styles.confirmTag, children: pkg.confirmTime === 0 ? '立即确认' : `${pkg.confirmTime}分钟确认` })] }), _jsxs("div", { className: styles.packageRight, children: [_jsxs("div", { className: styles.priceInfo, children: [_jsxs("span", { className: styles.originalPrice, children: ["\u00A5", room.priceList?.find(p => p.packageId === pkg.packageId)?.originPrice] }), _jsxs("span", { className: styles.currentPrice, children: ["\u00A5", room.priceList?.find(p => p.packageId === pkg.packageId)?.currentPrice] })] }), _jsx("button", { className: styles.selectBtn, onClick: (e) => {
                                                e.stopPropagation();
                                                onOpenDetail?.(room, pkg.packageId);
                                            }, children: "\u9884\u8BA2" })] })] }, pkg.packageId)))] })] })) }));
};
export default RoomCard;
//# sourceMappingURL=index.js.map