export { createApiService, createMockApiService } from './api';
export type { IApiService, ApiConfig, ApiResponse, PaginatedResponse } from './api';
export { registerStorage, useStorage, webStorageImpl, createTaroStorageImpl, } from './adapters/storage';
export type { IStorage } from './adapters/storage';
export { createHotelStore, initHotelStore, useHotelStore, resetHotelStore, } from './stores/hotelStore';
export type { SearchParams } from './stores/hotelStore';
export { useAppStore } from './stores/appStore';
export type { AppStoreState } from './stores/appStore';
export { useHomestayStore } from './stores/homestayStore';
export type { HomestayStoreState, DetailContextState, SearchUIState, } from './stores/homestayStore';
export { SEARCH_RESULT_HOMESTAYS, getRecommendedHomestays, POPULAR_HOMESTAYS, HOMESTAY_DETAIL_MOCK } from './mocks';
export { NEARBY_ROOMS } from './mocks';
export { FACILITY_CATEGORIES, getFacilitiesByCategory, getAvailableFacilitiesByCategory, getFacilitiesSectionData, getFacilitiesInCategory, getFacilitiesWithStatus } from './constants/facilities';
export type { Facility, FacilityCategory } from './constants/facilities';
export { MiddlewareManager, getMiddlewareManager, initializeDefaultMiddlewares, createLoggingMiddleware, createPerformanceMiddleware, } from './middleware';
export type { IMiddleware } from './middleware';
export { DETAIL_CENTER_DATA_MOCK } from './mocks/detailCenterData';
export { ErrorCode, BusinessError, ErrorFactory, ErrorHandlerChain, getErrorHandlerChain, handleError, } from './errors';
export type { IErrorHandler } from './errors';
export { ConfigManager, initializeConfig, getConfig, getConfigValue } from './config';
export type { Environment, ApiConfig as ConfigApiConfig, AuthConfig, StorageConfig, LoggingConfig, AppConfig, } from './config';
export { PersistenceManager, getPersistenceManager } from './persistence';
export type { SearchHistory, FavoriteHotel, UserPreferences } from './persistence';
export * from './types';
export * from './domain';
export { QUICK_FILTER_TAGS } from './constants/homestay';
export * from './utils';
//# sourceMappingURL=index.d.ts.map